### ISSUE TITLE
Url pattern does not allow parameters

### ISSUE THREAD

**Issue by jenswl** [Wrongsides/Gherkin-Viewer#3]
Hello,

first of all - thanks for writing this nice extension. From what I currently can see it does not support Gherkin for Urls that have parameters - e.g. if using stash and opening the raw view - there is always a paramterer like that:

someFile.feature?at=a682d919e4f827bacb85e4af66ab3d9970&raw

In the manifest file it's like that:

   "http://*/*.feature",
    "https://*/*.feature"

Could you please adjust it to *.feature* ?

Thank you very much,

Jens

**Comment by Wrongsides** [comment]
Hi,

Thanks Jens, I hadn't thought of this, I'm just a bit wary of the extension messing with unintended URLs for example:

features.myorganisation.com

would be presumed to be a feature file (which it may not be). I'm thinking if I add additional matches for 

file://*/*.feature?*
http://*/*.feature?*
https://*/*.feature?*

that should cover feature files with perameters & hopefully not interfear with peoples standard browsing experiance. I'll make this change to the project asap so I can test it, and look at updating the chrome store app after that.

**Comment by jenswl** [comment]
The pattern you proposed in your last comment should fit better than my one.

Beside that I just discovered that in case of watching a feature file in Stash it creates a https://myUrl/test.feature URL - but providing the whole Stash UI components around it. That means that in your current implementation the plugin would destroy the page layout. A solution could be to check for differences between your initial feature file source code (did you want to apply it on regular html content as well?) and a normal (html site) by e.g. searching for certain tags before applying the css changes.

Best regards,

Jens

**Comment by Wrongsides** [comment]
Sorted the pattern matching, should work now, but yes page layouts are going to be broken :( I would like it to format the Gherkin only within the actual Gherkin text. Should be able to do that if I inject between the tags rather than the whole page but I'll have to do a bit of research and prototyping first, I'll look into this next I think, then examples support and then take on the multi language support.
